### ISSUE TITLE
Sample plugins to exercise each extension point

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#25]
It's nice to come up with a series of sample plugins to exercise each extension point, and accompanied with a README guiding newcomers on how that's built.

Generally, the use-cases that the sample plugin tries to solve can be _hypothetical_, however, we do hope it's a or part of a problem in real-case world.

- [x] Sort - A QOS Sort plugin to sort the pods by their QOS level. #3
- [ ] PreFilter
- [ ] Filter
- [x] PostFilter - A cross-node preemption PostFitler plugin to try preempting pods on multiple nodes #56 
- [ ] PreScore
- [x] Score & NormalizeScore - A Score plugin to take (1) terminating Pods and (2) nominated Pods into accounts #103
- [ ] Permit
- [ ] Reserve
- [ ] PreBind
- [ ] Bind

**Comment by yuchen-sun** [comment]
Hi @Huang-Wei  can I do this task?

**Comment by denkensk** [comment]
> Hi @Huang-Wei can I do this task?

@yuchen-sun Of course, you can comment here which plugin you are interested in and take it to do.

**Comment by Huang-Wei** [comment]
@yuchen-sun Sure, which bullet you want to work on?

**Comment by yuchen-sun** [comment]
@Huang-Wei @denkensk THX,may be PreFilter plugin

**Comment by Huang-Wei** [comment]
Feel free to take it, and it would be nice if you can think of a use case for that.

**Comment by lianghao208** [comment]
Is that possible these series of sample plugins  become a new opensource project that newcomers can easily build?

**Comment by lianghao208** [comment]
@Huang-Wei, @denkensk Can I add a sample in pkg/qos that use prefilterPlugin to ignore the Pods which is in BestEffort (requests and limits not set) QOS level? it`s not a regular function but an example exercise tho.  Any suggestions?

**Comment by Huang-Wei** [comment]
@lianghao208 The example would depend on the schdule-delay annotation, right? If so, I don't quite think the sample would make a lot of sense. I believe there should be a better example to demonstrate PreFilter without relying on a "fake" annotation, WDYT?

**Comment by lianghao208** [comment]
@Huang-Wei I think CrossNodePreemption plugin need a preFilter extension point to filter the pods which don`t have priority or PreemptionPolicy has been set to Never. The basic logic is in  _PodEligibleToPreemptOthers_ method of default_preemption, which  will be invoked in preempt stage, Is it better to split the  _PodEligibleToPreemptOthers_ to the prefilter stage? WDYT?

**Comment by Huang-Wei** [comment]
> I think CrossNodePreemption plugin need a preFilter extension point to filter the pods which don`t have priority or PreemptionPolicy has been set to Never.

That's not true. All extension points are all targeting the incoming Pod, not existing Pods.

**Comment by lianghao208** [comment]
> 
> That's not true. All extension points are all targeting the incoming Pod, not existing Pods.
It is targeting the incoming Pods. The preFilter plugin filter the incoming pods which don`t have priority or PreemptionPolicy has been set to Never, does it make sense?

**Comment by Huang-Wei** [comment]
> The preFilter plugin filter the incoming pods which don`t have priority or PreemptionPolicy has been set to Never, does it make sense?

It only makes sense in PostFilter(), not PreFilter(). And note that a Pod would always have a `.spec.priority` - defaults to 0. And also be aware that users may set a negative Priority. It's tracked in https://github.com/kubernetes/kubernetes/issues/89036 and attempted in https://github.com/kubernetes/kubernetes/pull/92875 (which assumes Priority 0 as the lowest priority, but proved to be incorrect.

As cross_node_preemption plugin aims to provide a sample on how to inspire users to craft cross node preempting logic, I don't like to confuse users with separate irrelevant optimization logic. Instead, it's welcomed to propose KEP/PR to get it implemented in k/k's default_preemption plugin.

**Comment by lianghao208** [comment]
> It only makes sense in PostFilter(), not PreFilter(). 

Thanks for the reply.
Does every single pod need to pass through the default_preemption plugin in the PostFilter() ? If so, how to schedule the pod that can`t pass the PodEligibleToPreemptOthers() ? ( Note that If a pod can`t pass PodEligibleToPreemptOthers(), PostFilter() returns Unschedulable status)

**Comment by lianghao208** [comment]
@Huang-Wei
 I incline to work on a Score plugin sample to score nodes taking terminating Pods and nominated Pods into accounts. But I can`t figure out the relationship between the terminating Pods and node. Does it mean the more terminating pods existing on nodes, the less score those nodes will get? Or the more pods set a node as a nominatedNode, the less score this node will get?

**Comment by Huang-Wei** [comment]
> Does every single pod need to pass through the default_preemption plugin in the PostFilter() ?

Only when (1) default_preemption is the first configured PostFilter plugin, or (2) the PostFilter plugins configured prior to default_preemption all failed.



> Does it mean the more terminating pods existing on nodes, the less score those nodes will get?

I think it makes sense to give those nodes a higher score, as those termnating Pods would be physically removed eventually, and hence release their claimed resources. In other words, the nodes with terminating Pods are more likely to be able to accommodate more pods.

While for nominated node, I think it would be good to give it a lower score, as that node is supposed to accordmorate some preemptor pod in a future scheduling cycle.

**Comment by lianghao208** [comment]
@Huang-Wei
Thanks, I would like to implement it and submit a PR.

**Comment by Huang-Wei** [comment]
> Thanks, I would like to implement it and submit a PR.

Sounds great. Thanks.

**Comment by yuchen-sun** [comment]
@Huang-Wei 
Sorry for the long delay.
For `prefilter` plugins, i hava a idea about quota.
we can use prefilter to limit pods which has **quote/resource-name:value** label.
Only when this **namespace resource usage + this pod request** <= **resources-quota-value**,return **Success**

**Comment by denkensk** [comment]
@yuchen-sun  Thanks  
We have a design document https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/kep/9-capacity-scheduling , you can see if it is similar to your idea

**Comment by yuchen-sun** [comment]
@denkensk  Thanks for the reply.
This design document looks good.It can improve resource utilization.
My idea was simply to allow one user to use only a limited amount of resources.

BTW: About this design doc,it similar to our internal ai platform.But,we are not allowed to  preempt,because some ML tasks cannot be interrupted.

**Comment by denkensk** [comment]
@yuchen-sun 
Thanks 
We can work together to make it better.

**Comment by seanmalloy** [comment]
@Huang-Wei is the check list in the issue description up to date?

/remove-lifecycle stale

**Comment by Huang-Wei** [comment]
@seanmalloy I updated it a bit. Now it's up to date.
