### ISSUE TITLE
migrate controllers and clients to leverage controller-runtime

### ISSUE THREAD

**Issue by zwpaper** [kubernetes-sigs/scheduler-plugins#485]
Scheduler Plugins is working on migrating controllers and clients to leverage `controller-runtime`, 

I have walked through the code base quickly and met some questions, so I am opening this issue to
make sure I am doing things right and figure out how can we work on this.

there should be 2 parts we should work on:
1. controllers: https://github.com/kubernetes-sigs/scheduler-plugins/tree/056fa7df192d4b49101650f37873338e3d8b96fb/pkg/controller, which is WIP with https://github.com/kubernetes-sigs/scheduler-plugins/tree/056fa7df192d4b49101650f37873338e3d8b96fb/pkg/controllers and not yet being used
2. generated clients: used everywhere in controllers and schedulers

my questions are:
1. is the 2 parts above right?
2. should we use a new command args to choose the legacy or controller-runtime controllers
3. should all the generated clients used in controllers and schedulers be migrated to controller-runtime clients?

# break down

## Controllers

- [x] Pod Group: @zwpaper https://github.com/kubernetes-sigs/scheduler-plugins/pull/506 
- [x] Elastic Quota: @czybjtu https://github.com/kubernetes-sigs/scheduler-plugins/pull/527

## clients

this is generated by the following cmd:

```sh
rg -c -l -g '!vendor' -g '!pkg/generated' -g '!*_test.go' 'pkg/generated/' . | sort
```

- [x] ./cmd/controller/app/server.go:2 https://github.com/kubernetes-sigs/scheduler-plugins/pull/569
- [x] ./pkg/capacityscheduling/capacity_scheduling.go:3 #665
- [x] ./pkg/controller/elasticquota.go:3 https://github.com/kubernetes-sigs/scheduler-plugins/pull/527
- [x] ./pkg/controller/podgroup.go:3: @zwpaper https://github.com/kubernetes-sigs/scheduler-plugins/pull/506 
- [x] ./pkg/coscheduling/core/core.go:3 #652
- [x] ./pkg/coscheduling/coscheduling.go:2 #652
- [x] ./pkg/networkaware/networkoverhead/networkoverhead.go:2 @zwpaper https://github.com/kubernetes-sigs/scheduler-plugins/pull/522
- [x] ./pkg/networkaware/topologicalsort/topologicalsort.go:1 @zwpaper https://github.com/kubernetes-sigs/scheduler-plugins/pull/522
- [x] ./pkg/networkaware/util/util.go:6 @zwpaper https://github.com/kubernetes-sigs/scheduler-plugins/pull/522
- [x] ./pkg/noderesourcetopology/cache/discardreserved.go:1 https://github.com/kubernetes-sigs/scheduler-plugins/pull/655
- [x] ./pkg/noderesourcetopology/cache/overreserve.go:1 https://github.com/kubernetes-sigs/scheduler-plugins/pull/655
- [x] ./pkg/noderesourcetopology/cache/passthrough.go:1 https://github.com/kubernetes-sigs/scheduler-plugins/pull/655
- [x] ./pkg/noderesourcetopology/pluginhelpers.go:2 https://github.com/kubernetes-sigs/scheduler-plugins/pull/655
- [x] ./test/integration/nrtutils.go:1 @zwpaper https://github.com/kubernetes-sigs/scheduler-plugins/pull/655
- [x] ./test/integration/utils.go:2 https://github.com/kubernetes-sigs/scheduler-plugins/pull/522

**Comment by zwpaper** [comment]
cc @Huang-Wei

**Comment by Huang-Wei** [comment]
> 1. is the 2 parts above right?

`pkg/controller` adopts typed clientset, which is currently used; `pkg/controllers` is WIP, and hence not being used in real logic for now. Our goal is to migrate to the general client (controller-runtime's), in other words, get rid of current typed clientsets (both usage and codegen).

> 2. should we use a new command args to choose the legacy or controller-runtime controllers

I'd prefer to adopt the latest conversion/best practice of adopting controller-runtime. No need to stick to the legacy way.

> 3. should all the generated clients used in controllers and schedulers be migrated to controller-runtime clients?

Yes. That's the point of migration - getting rid of typed clients.

**Comment by zwpaper** [comment]
I will start to work on migrating Pod Group controller

/assign

**Comment by Huang-Wei** [comment]
@czybjtu you may want to contact @zwpaper first. (just to ensure you are not working on the same item)

**Comment by czybjtu** [comment]
sorry for my oversight. Please let me know if you have started working on it. @zwpaper

**Comment by zwpaper** [comment]
Oops, I should leave a comment rather than just updating the issue description.

it is totally great for anyone to participate, and accelerate the migration.

I have done the podGroup controller migration, you can refer to it and it may save some of your time. @czybjtu 

Now I am starting to work on the migration of scheduler clients, feel free to ping me if anyone would like to participate.

cc @Huang-Wei

**Comment by ffromani** [comment]
/cc
I'd be happy to check if `noderesourcetopology` (and later other plugins hopefully) need some work

**Comment by Huang-Wei** [comment]
@zwpaper I'm working on coscheduling's migration to controller-runtime.

**Comment by Huang-Wei** [comment]
Last piece of migrate elasticquota/capacityscheduling #665

**Comment by Huang-Wei** [comment]
All work completed. Thanks a ton for @zwpaper to lead the migration work.

I added some notes in the release note: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.27.8. In particular:

---

One major change completed in this release is https://github.com/kubernetes-sigs/scheduler-plugins/issues/485 which migrates from typed client to generic controller-runtime client.

- Impact to end-users: N/A
- Impact to developers:
  - for CR object's manipulation, new plugin's development should stick to current codebase convention to use controller-runtime's client or informer
  - for core API object's manipulation, esp. Pods and Nodes, it's still recommended to read/watch from frameworkHandle's sharedInformerFactory; for other core API objects, it's up to plugin developers to choose which client to use
  - ⚠️ generated typed client/informer under [pkg/generated](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/generated) will be removed after 3 releases (v0.30.x). External repos that vendor this repo's typed generation code should either generate typed client/informer themselves or start migrating to generic controller-runtime client.
