### ISSUE TITLE
Release 0.25

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#540]
```[tasklist]
# Tasks
- [ ] https://github.com/kubernetes/k8s.io/pull/4890
- [ ] #541
- [ ] https://github.com/kubernetes/test-infra/pull/28936
- [x] Release page for v0.25.7: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.25.7
```

## Refs: 

- [release process](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/RELEASE.md)
- [🔒 staging images](https://console.cloud.google.com/gcr/images/k8s-staging-scheduler-plugins/GLOBAL/kube-scheduler?gcrImageListsize=30&pli=1)
- [testgrid:post-scheduler-plugins-push-images](https://testgrid.k8s.io/sig-scheduling#post-scheduler-plugins-push-images)

**Comment by Huang-Wei** [comment]
All tasks have been completed.
