### ISSUE TITLE
Release 0.26

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#603]
```[tasklist]
# Tasks
- [x] cut new branch `release-1.26`: https://github.com/kubernetes-sigs/scheduler-plugins/tree/release-1.26
- [ ] https://github.com/kubernetes/test-infra/pull/30196
- [x] tag cutting: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.26.7
- [ ] https://github.com/kubernetes/k8s.io/pull/5630
- [ ] #604
- [x] Release page for v0.26.7: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.26.7
```

## Refs: 

- [release process](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/RELEASE.md)
- [🔒 staging images](https://console.cloud.google.com/gcr/images/k8s-staging-scheduler-plugins/GLOBAL/kube-scheduler?gcrImageListsize=30&pli=1)
- [testgrid:post-scheduler-plugins-push-images](https://testgrid.k8s.io/sig-scheduling#post-scheduler-plugins-push-images)

**Comment by Huang-Wei** [comment]
All items completed. Close this issue.

**Comment by Huang-Wei** [comment]
btw: from this release, I started to use [Kubernetes Release Notes Generator](https://github.com/kubernetes/release/blob/master/cmd/release-notes/README.md) to generate the release notes.

```
release-notes --start-sha 3d7104edb4b9805b76e42d202ed28cb50d42de13 --end-sha fb9bf41378a78e365c570bfb31a30e8e739996e1 --org kubernetes-sigs --repo scheduler-plugins
```

Let's ensure changes are always well documented in each PR using the `release-notes` section :)
