### ISSUE TITLE
Tracking: status for Page site

### ISSUE THREAD

**Issue by zwpaper** [kubernetes-sigs/scheduler-plugins#620]
### Area

- [X] Helm Chart
- [X] Documents

### What happened?

We are setting up a GitHub Page site for Scheduler Plugin, there are some tasks we need to do, and we should track its status

### What did you expect to happen?

- [x] use Netlify to build a Page: https://github.com/kubernetes-sigs/scheduler-plugins/pull/616
- [x] set up the netlify page: https://github.com/kubernetes/org/issues/4387
- [x] set up the cname DNS, https://github.com/kubernetes/k8s.io/pull/5775
- [ ] release a helm chart in GitHub Release
- [ ] (not yet sure needed or how to) set up GitHub Action to include the helm chart index in the Scheduler Plugins site

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Scheduler Plugins version

<details>

</details>

**Comment by zwpaper** [comment]
/remove-lifecycle stale
I will look into this recently
