### ISSUE TITLE
Release 0.27

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#662]
```[tasklist]
# Tasks
- [x] cut new branch https://github.com/kubernetes-sigs/scheduler-plugins/tree/release-1.27
- [x] https://github.com/kubernetes/test-infra/pull/31260
- [x] tag cutting: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.27.8
- [x] https://github.com/kubernetes/k8s.io/pull/6096
- [ ] #669
- [x] Release page: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.27.8
- [x] Announcement email sent to sig-scheduling mailing group: https://groups.google.com/g/kubernetes-sig-scheduling/c/BczC-5aAlOw/m/l3qSLDrFAAAJ
```

## Refs: 

- [release process](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/RELEASE.md)
- [🔒 staging images](https://console.cloud.google.com/gcr/images/k8s-staging-scheduler-plugins/GLOBAL/kube-scheduler?gcrImageListsize=30&pli=1)
- [testgrid:post-scheduler-plugins-push-images](https://testgrid.k8s.io/sig-scheduling#post-scheduler-plugins-push-images)

Fixes #651

**Comment by tenzen-y** [comment]
Hi, @Huang-Wei. Thanks for moving this forward. I'm looking forward to the new release.
BTW, do you have any estimated day to cut a new release?

**Comment by Huang-Wei** [comment]
@tenzen-y today I'm gonna raise a final PR to migrate the typed client usage in capacityscheduling pkg to controller-runtime. After this is done, I will get the new release cut. ETA is end of this week.

Thanks for the patience ;)

**Comment by tenzen-y** [comment]
> @tenzen-y today I'm gonna raise a final PR to migrate the typed client usage in capacityscheduling pkg to controller-runtime. After this is done, I will get the new release cut. ETA is end of this week.
> 
> Thanks for the patience ;)

Thanks for your effort!

**Comment by Huang-Wei** [comment]
@tenzen-y you're good to go use v0.27.8 release.

**Comment by tenzen-y** [comment]
> @tenzen-y you're good to go use v0.27.8 release.

Thank you so much!
