### ISSUE TITLE
Release 0.28

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#715]
```[tasklist]
# Tasks
- [x] cut new branch https://github.com/kubernetes-sigs/scheduler-plugins/tree/release-1.28
- [ ] https://github.com/kubernetes/test-infra/pull/32444
- [x] tag cutting: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.28.9
- [ ] https://github.com/kubernetes/k8s.io/pull/6705
- [ ] https://github.com/kubernetes-sigs/scheduler-plugins/pull/719
- [x] Release page: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.28.9
- [x] Announcement email sent to sig-scheduling mailing group: https://groups.google.com/g/kubernetes-sig-scheduling/c/SeVzaeVtImM/m/Fi7fmyIKAwAJ
```

## Refs: 

- [release process](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/RELEASE.md)
- [🔒 staging images](https://console.cloud.google.com/gcr/images/k8s-staging-scheduler-plugins/GLOBAL/kube-scheduler?gcrImageListsize=30&pli=1)
- [testgrid:post-scheduler-plugins-push-images](https://testgrid.k8s.io/sig-scheduling#post-scheduler-plugins-push-images)

**Comment by Huang-Wei** [comment]
I noticed a glitch: I forgot to include include #700 in v0.28.8, so I have to bump the version to v0.28.9 to include [it](https://github.com/kubernetes-sigs/scheduler-plugins/pull/718).
