### ISSUE TITLE
Release 0.29

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#776]
```[tasklist]
# Tasks
- [x] cut new branch https://github.com/kubernetes-sigs/scheduler-plugins/tree/release-1.29
- [ ] https://github.com/kubernetes/test-infra/pull/33135
- [x] tag cutting: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.29.7
- [ ] publish scheduler-plugins v0.29.7 (k/k8s.io)
- [ ] update Helm chart (e.g., #737)
- [ ] #775
- [ ] Release page: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.29.7
- [ ] Announcement email sent to sig-scheduling mailing group: 
```

```[tasklist]
# Post-release TODOs
- [ ] Update k8s deps to 1.30 in `master` branch
- [ ] Update test-infra's pre-submit jobs to use correct Golang version
- [ ] Cut a `v0.30.X-devel` tag
```

## Refs: 

- [release process](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/RELEASE.md)
- [🔒 staging images](https://console.cloud.google.com/gcr/images/k8s-staging-scheduler-plugins/GLOBAL/kube-scheduler?gcrImageListsize=30&pli=1)
- [testgrid:post-scheduler-plugins-push-images](https://testgrid.k8s.io/sig-scheduling#post-scheduler-plugins-push-images)

**Comment by Huang-Wei** [comment]
Close as completed.
