### ISSUE TITLE
Release 0.30

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#819]
```[tasklist]
# Tasks
- [x] cut new branch https://github.com/kubernetes-sigs/scheduler-plugins/tree/release-1.30
- [ ] https://github.com/kubernetes/test-infra/pull/33749
- [x] tag cutting: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.30.6
- [ ] https://github.com/kubernetes/k8s.io/pull/7477
- [ ] #820
- [ ] #822
- [x] Release page: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.30.6
- [x] Announcement [email](https://groups.google.com/g/kubernetes-sig-scheduling/c/6ofUCK7ynxw/m/7THMwnoZBgAJ) sent to sig-scheduling mailing group
```

```[tasklist]
# Post-release TODOs
- [ ] #832
- [x] Cut a `v0.31.2-devel` tag
```

## Refs: 

- [release process](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/RELEASE.md)
- [🔒 staging images](https://console.cloud.google.com/gcr/images/k8s-staging-scheduler-plugins/GLOBAL/kube-scheduler?gcrImageListsize=30&pli=1)
- [testgrid:post-scheduler-plugins-push-images](https://testgrid.k8s.io/sig-scheduling#post-scheduler-plugins-push-images)

**Comment by Huang-Wei** [comment]
All tasks have been completed.
